version: '2'

services:
  david-op:
    build: .
    command: >
    gunicorn -b 0.0.0.0:8000
    --access-logfile -
    --reload
    "david-op.app:create_app()"
    environment:
      PYTHONUNBUFFERED:
    volumes:
      - '.:/david-op'
    ports:
      - '8000:8000'